apiVersion: apps/v1
kind: Deployment
metadata:
  name: Nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Nodejs
  template:
    metadata:
      labels:
        app: Nodejs
    spec:
      containers:
      - name: Nodejs
        image: 711387141897.dkr.ecr.ap-south-1.amazonaws.com/my-ecr-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
